---
- name: Example Ansible Playbook
  hosts: webserver
  tasks:
    - name: Run a command on the remote SSH server
      ansible.builtin.shell: ssh -o StrictHostKeyChecking=no root@172.17.0.2 -p 2222
      register: result

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Display the command output
      debug:
        var: result.stdout_lines
